FROM ruby:2.3

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs cron telnet redis-server supervisor

RUN mkdir /chart_app
WORKDIR /chart_app

ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN gem install bundler
# RUN bundle install --without development test
RUN bundle install


